"""
KEYM v1 — independent reference implementation.

Written **only** from docs/FORMAT.md. It deliberately imports nothing from the
TypeScript implementation and was not derived from it.

That independence is the entire point. The frozen fixtures under
scripts/fixtures/keymaker/ were generated by the same code they test, so a
misreading of the specification would be baked identically into implementation
and vectors and would look like agreement forever. A second implementation,
written from the prose, is what turns those fixtures from a self-consistency
check into a conformance test: if this file and the TypeScript disagree, one of
them is wrong, and the specification is what decides which.

Dependencies:
    cryptography    AES-256-GCM, ChaCha20-Poly1305, HKDF, PBKDF2
    argon2-cffi     Argon2id

Usage:
    python -m reference.keym encrypt --password P --kdf argon2id --cipher chained
    python -m reference.keym decrypt --password P < container.keym
    python -m reference.keym selftest
"""

from __future__ import annotations

import argparse
import errno
import os
import struct
import sys
import unicodedata
from dataclasses import dataclass
from typing import Optional

from argon2.low_level import Type as Argon2Type, hash_secret_raw
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

# ---------------------------------------------------------------- constants
# FORMAT.md section 1 and 2.

MAGIC = b"KEYM"
VERSION = 1

KDF_PBKDF2 = 0x00
KDF_ARGON2ID = 0x01

CIPHER_AES_256_GCM = 0x00
CIPHER_CHACHA20_POLY1305 = 0x01
CIPHER_CHAINED = 0x02

SALT_LEN_PBKDF2 = 16
SALT_LEN_ARGON2ID = 32
NONCE_LEN = 12
TAG_LEN = 16
KEY_LEN = 32

# FORMAT.md section 4: bit 0 signals a key file was used at encryption time.
FLAG_KEYFILE = 0x01

# FORMAT.md section 6: HKDF labels for the chained cipher's subkeys.
HKDF_INFO_AES = b"keymaker-aes"
HKDF_INFO_CHACHA = b"keymaker-chacha"


# FORMAT.md section 3.1 (NORMATIVE): cost parameters must be bounded before
# any key derivation runs. Upper bounds are the security control and apply when
# reading; lower bounds are policy for newly written containers only, so that
# legitimately weak historical files still open.
#
# This section was added to the specification *because* of this file. Written
# from the prose as it stood, the reference faithfully reproduced the
# unbounded behaviour and blew up allocating ~2.5 GiB when the cross-test
# flipped a kdf_id byte. The TypeScript already had the bounds; the spec did
# not, so any independent implementation would have inherited the flaw.
MAX_PBKDF2_ITERATIONS = 10_000_000
MIN_PBKDF2_ITERATIONS_WRITE = 600_000
MAX_ARGON2_TIME_COST = 10
MAX_ARGON2_MEMORY_KIB = 262_144
MIN_ARGON2_MEMORY_KIB_WRITE = 8_192
MAX_ARGON2_PARALLELISM = 8


class KeymError(Exception):
    """Any parse or authentication failure. Deliberately undifferentiated."""


def validate_params(kdf_id: int, params, writing: bool) -> None:
    """FORMAT.md section 3.1. Must run before any key derivation."""

    def check(name: str, value: int, low: int, high: int) -> None:
        if not isinstance(value, int) or value < low or value > high:
            raise KeymError(f"{name} out of range: {value} not in {low}..{high}")

    if kdf_id == KDF_PBKDF2:
        check(
            "pbkdf2 iterations",
            params.iterations,
            MIN_PBKDF2_ITERATIONS_WRITE if writing else 1,
            MAX_PBKDF2_ITERATIONS,
        )
        return

    check("argon2 time_cost", params.time_cost, 1, MAX_ARGON2_TIME_COST)
    check(
        "argon2 memory_kib",
        params.memory_kib,
        MIN_ARGON2_MEMORY_KIB_WRITE if writing else 1,
        MAX_ARGON2_MEMORY_KIB,
    )
    check("argon2 parallelism", params.parallelism, 1, MAX_ARGON2_PARALLELISM)


@dataclass
class Pbkdf2Params:
    iterations: int


@dataclass
class Argon2idParams:
    time_cost: int
    memory_kib: int
    parallelism: int


@dataclass
class Header:
    kdf_id: int
    cipher_id: int
    params: object
    flags: int
    salt: bytes
    nonces: list[bytes]
    settings_block: bytes  # magic .. last nonce, the AAD
    ciphertext: bytes


# ------------------------------------------------------------ key derivation


def _base_material(password: str, key_file: Optional[bytes]) -> bytes:
    """
    FORMAT.md section 6, steps 1-2.

    NFC-normalise, encode UTF-8, then append the raw key file bytes. The
    concatenation is unseparated — noted in the spec as inherited from the
    legacy format.
    """
    material = unicodedata.normalize("NFC", password).encode("utf-8")
    if key_file:
        material += key_file
    return material


def _derive_master_key(material: bytes, salt: bytes, kdf_id: int, params) -> bytes:
    """FORMAT.md section 6, step 3."""
    if kdf_id == KDF_PBKDF2:
        return PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=KEY_LEN,
            salt=salt,
            iterations=params.iterations,
        ).derive(material)

    if kdf_id == KDF_ARGON2ID:
        return hash_secret_raw(
            secret=material,
            salt=salt,
            time_cost=params.time_cost,
            memory_cost=params.memory_kib,
            parallelism=params.parallelism,
            hash_len=KEY_LEN,
            type=Argon2Type.ID,
        )

    raise KeymError(f"unknown kdf_id {kdf_id}")


def _subkeys(master: bytes) -> tuple[bytes, bytes]:
    """
    FORMAT.md section 6, step 4: HKDF-SHA-256 with a zero (absent) salt and the
    two distinct info labels.
    """

    def expand(info: bytes) -> bytes:
        return HKDF(algorithm=hashes.SHA256(), length=KEY_LEN, salt=None, info=info).derive(master)

    return expand(HKDF_INFO_AES), expand(HKDF_INFO_CHACHA)


# ------------------------------------------------------------------ parsing


def parse(data: bytes) -> Header:
    """FORMAT.md sections 1-5."""
    if len(data) < 8:
        raise KeymError("too short")
    if data[0:4] != MAGIC:
        raise KeymError("bad magic")
    if data[4] != VERSION:
        raise KeymError(f"unsupported version {data[4]}")

    kdf_id = data[5]
    cipher_id = data[6]
    if kdf_id not in (KDF_PBKDF2, KDF_ARGON2ID):
        raise KeymError(f"unknown kdf_id {kdf_id}")
    if cipher_id not in (CIPHER_AES_256_GCM, CIPHER_CHACHA20_POLY1305, CIPHER_CHAINED):
        raise KeymError(f"unknown cipher_id {cipher_id}")

    off = 7
    if kdf_id == KDF_PBKDF2:
        # section 3: 4 bytes, uint32 big-endian iteration count.
        (iterations,) = struct.unpack_from(">I", data, off)
        params: object = Pbkdf2Params(iterations)
        off += 4
        salt_len = SALT_LEN_PBKDF2
    else:
        # section 3: uint16 time_cost, uint32 memory_kib, uint8 parallelism.
        time_cost, memory_kib = struct.unpack_from(">HI", data, off)
        parallelism = data[off + 6]
        params = Argon2idParams(time_cost, memory_kib, parallelism)
        off += 7
        salt_len = SALT_LEN_ARGON2ID

    # FORMAT.md section 3.1: bound the cost parameters here, before anything
    # can hand them to a KDF. Everything read above this point is untrusted —
    # the tag that authenticates it cannot be checked until after derivation.
    validate_params(kdf_id, params, writing=False)

    flags = data[off]
    off += 1

    nonce_count = 2 if cipher_id == CIPHER_CHAINED else 1
    needed = off + salt_len + nonce_count * NONCE_LEN + TAG_LEN
    if len(data) < needed:
        raise KeymError("too short for declared parameters")

    salt = data[off : off + salt_len]
    off += salt_len

    nonces = []
    for _ in range(nonce_count):
        nonces.append(data[off : off + NONCE_LEN])
        off += NONCE_LEN

    # section 7: the settings block is magic through the last nonce byte.
    return Header(
        kdf_id=kdf_id,
        cipher_id=cipher_id,
        params=params,
        flags=flags,
        salt=salt,
        nonces=nonces,
        settings_block=data[:off],
        ciphertext=data[off:],
    )


def build_header(
    kdf_id: int, cipher_id: int, params, flags: int, salt: bytes, nonces: list[bytes]
) -> bytes:
    out = bytearray()
    out += MAGIC
    out.append(VERSION)
    out.append(kdf_id)
    out.append(cipher_id)
    if kdf_id == KDF_PBKDF2:
        out += struct.pack(">I", params.iterations)
    else:
        out += struct.pack(">HI", params.time_cost, params.memory_kib)
        out.append(params.parallelism)
    out.append(flags)
    out += salt
    for n in nonces:
        out += n
    return bytes(out)


# --------------------------------------------------------------- encryption


def encrypt(
    plaintext: bytes,
    password: str,
    key_file: Optional[bytes] = None,
    kdf_id: int = KDF_ARGON2ID,
    params=None,
    cipher_id: int = CIPHER_AES_256_GCM,
) -> bytes:
    """FORMAT.md sections 6-8."""
    if params is None:
        params = (
            Pbkdf2Params(1_000_000)
            if kdf_id == KDF_PBKDF2
            else Argon2idParams(3, 65536, 4)
        )

    validate_params(kdf_id, params, writing=True)

    salt_len = SALT_LEN_PBKDF2 if kdf_id == KDF_PBKDF2 else SALT_LEN_ARGON2ID
    salt = os.urandom(salt_len)
    nonce_count = 2 if cipher_id == CIPHER_CHAINED else 1
    nonces = [os.urandom(NONCE_LEN) for _ in range(nonce_count)]
    flags = FLAG_KEYFILE if key_file else 0x00

    settings = build_header(kdf_id, cipher_id, params, flags, salt, nonces)
    master = _derive_master_key(_base_material(password, key_file), salt, kdf_id, params)

    if cipher_id == CIPHER_AES_256_GCM:
        body = AESGCM(master).encrypt(nonces[0], plaintext, settings)
    elif cipher_id == CIPHER_CHACHA20_POLY1305:
        body = ChaCha20Poly1305(master).encrypt(nonces[0], plaintext, settings)
    else:
        # section 8: AES inner, then ChaCha outer, both with the same AAD.
        aes_key, chacha_key = _subkeys(master)
        inner = AESGCM(aes_key).encrypt(nonces[0], plaintext, settings)
        body = ChaCha20Poly1305(chacha_key).encrypt(nonces[1], inner, settings)

    return settings + body


def decrypt(container: bytes, password: str, key_file: Optional[bytes] = None) -> bytes:
    """FORMAT.md sections 7-8, reversed."""
    h = parse(container)

    try:
        # Inside the try: a KDF backend can fail on its own terms (allocation,
        # unsupported parameters) and that must surface as the same generic
        # failure as a bad tag, not as a distinguishable backend exception.
        master = _derive_master_key(
            _base_material(password, key_file), h.salt, h.kdf_id, h.params
        )

        if h.cipher_id == CIPHER_AES_256_GCM:
            return AESGCM(master).decrypt(h.nonces[0], h.ciphertext, h.settings_block)
        if h.cipher_id == CIPHER_CHACHA20_POLY1305:
            return ChaCha20Poly1305(master).decrypt(
                h.nonces[0], h.ciphertext, h.settings_block
            )
        aes_key, chacha_key = _subkeys(master)
        inner = ChaCha20Poly1305(chacha_key).decrypt(
            h.nonces[1], h.ciphertext, h.settings_block
        )
        return AESGCM(aes_key).decrypt(h.nonces[0], inner, h.settings_block)
    except Exception as exc:  # noqa: BLE001 - generic by design
        # Section 10: errors are generic so they cannot act as an oracle.
        raise KeymError("decryption failed") from exc


# --------------------------------------------------------------------- CLI


def _selftest() -> int:
    """Round-trip this implementation against itself. Not a conformance test."""
    failures = 0
    fast_argon = Argon2idParams(2, 16384, 2)
    # At the write floor from FORMAT.md section 3.1, not below it.
    fast_pbkdf2 = Pbkdf2Params(600_000)

    for kdf_id, params in ((KDF_PBKDF2, fast_pbkdf2), (KDF_ARGON2ID, fast_argon)):
        for cipher_id in (CIPHER_AES_256_GCM, CIPHER_CHACHA20_POLY1305, CIPHER_CHAINED):
            for kf in (None, bytes(range(32))):
                pt = "self-test — ünïcode ✅".encode("utf-8")
                ct = encrypt(pt, "pw", kf, kdf_id, params, cipher_id)
                got = decrypt(ct, "pw", kf)
                ok = got == pt
                print(f"  {'ok  ' if ok else 'FAIL'} kdf={kdf_id} cipher={cipher_id} keyfile={kf is not None}")
                failures += 0 if ok else 1
    print("selftest passed" if not failures else f"{failures} failures")
    return 1 if failures else 0


KDF_NAMES = {KDF_PBKDF2: "PBKDF2-HMAC-SHA-256", KDF_ARGON2ID: "Argon2id"}
CIPHER_NAMES = {
    CIPHER_AES_256_GCM: "AES-256-GCM",
    CIPHER_CHACHA20_POLY1305: "ChaCha20-Poly1305",
    CIPHER_CHAINED: "AES-256-GCM then ChaCha20-Poly1305 (chained)",
}


def read_container(path: str | None) -> bytes:
    """
    Load a container from a file or stdin, accepting either wire form.

    Keymaker writes files as raw bytes (.keym) but text as base64 behind a
    "KEYM1:" prefix, and people back up whichever they were handed — a pasted
    blob in a password manager is as likely as a downloaded file. A recovery
    tool that only understood one of them would fail for reasons the person
    holding it could not diagnose.
    """
    raw = _read_bytes(path)

    # Check the text prefix *before* the magic bytes: "KEYM1:" begins with the
    # same four ASCII characters as the binary magic, so a magic-first test
    # misreads a text backup as a raw container and then rejects it for having
    # version 0x31 ("1"). A binary container has 0x01 at that offset.
    is_text = raw[:6].upper() == b"KEYM1:"
    if not is_text and raw[:4] == MAGIC:
        return raw

    # Text form, tolerating the prefix and any wrapping whitespace.
    import base64

    try:
        text = raw.decode("utf-8").strip()
    except UnicodeDecodeError as exc:
        raise KeymError("input is neither a KEYM file nor KEYM1: base64 text") from exc
    if text.upper().startswith("KEYM1:"):
        text = text[len("KEYM1:") :]
    text = "".join(text.split())
    try:
        decoded = base64.b64decode(text, validate=True)
    except Exception as exc:  # noqa: BLE001
        raise KeymError(
            "input is neither a KEYM file nor KEYM1: base64 text"
        ) from exc
    if decoded[:4] != MAGIC:
        raise KeymError("decoded data is not a KEYM container (bad magic)")
    return decoded


def resolve_password(supplied: str | None, confirm: bool = False) -> str:
    """
    Prefer an interactive prompt over --password.

    A password passed as an argument lands in shell history and is visible in
    the process list to every other user on the machine, for as long as the
    KDF runs — which for Argon2id is seconds, by design. That is the wrong
    default for a tool whose entire job is handling someone's real secret.
    """
    if supplied is not None:
        print(
            "warning: --password was read from the command line, so it is now in "
            "your shell history and was visible in the process list. Prefer the "
            "interactive prompt for real secrets.",
            file=sys.stderr,
        )
        return supplied

    import getpass

    pw = getpass.getpass("Password: ")
    if confirm and pw != getpass.getpass("Confirm password: "):
        raise KeymError("passwords did not match")
    return pw


def _inspect(container: bytes) -> int:
    """
    Describe a container without decrypting it.

    Everything printed here comes from the header, which is readable before
    any key exists — that is the point of a self-describing format. It is also
    authenticated (FORMAT.md section 7), so a successful later decryption
    proves these values were not tampered with. Before that, treat them as
    claims the file makes about itself.
    """
    h = parse(container)
    print(f"format          KEYM v{VERSION}")
    print(f"key derivation  {KDF_NAMES[h.kdf_id]}")
    if h.kdf_id == KDF_PBKDF2:
        print(f"                iterations {h.params.iterations:,}")
    else:
        print(
            f"                time cost {h.params.time_cost}, "
            f"memory {h.params.memory_kib // 1024} MiB, "
            f"parallelism {h.params.parallelism}"
        )
    print(f"cipher          {CIPHER_NAMES[h.cipher_id]}")
    print(f"key file        {'required' if h.flags & FLAG_KEYFILE else 'not used'}")
    print(f"salt            {len(h.salt)} bytes")
    print(f"nonces          {len(h.nonces)} x {NONCE_LEN} bytes")
    print(f"header          {len(h.settings_block)} bytes (authenticated as AAD)")
    print(f"ciphertext      {len(h.ciphertext)} bytes")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        prog="keym",
        description=(
            "KEYM v1 reference implementation and offline recovery tool. "
            "Decrypts any Keymaker container without a browser."
        ),
        epilog="See docs/RECOVERY.md for the standalone recovery procedure.",
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    for name in ("encrypt", "decrypt"):
        p = sub.add_parser(name, help=f"{name} a KEYM container")
        p.add_argument(
            "--password",
            help="not recommended: leaks to shell history and the process list. "
            "Omit to be prompted.",
        )
        p.add_argument("--key-file", help="path to the key file, if one was used")
        p.add_argument("--in", dest="infile", help="input path (default: stdin)")
        p.add_argument("--out", dest="outfile", help="output path (default: stdout)")
        if name == "encrypt":
            p.add_argument("--kdf", choices=["pbkdf2", "argon2id"], default="argon2id")
            p.add_argument("--cipher", choices=["aes", "chacha", "chained"], default="aes")
            p.add_argument("--iterations", type=int, default=1_000_000)
            p.add_argument("--time-cost", type=int, default=3)
            p.add_argument("--memory-kib", type=int, default=65536)
            p.add_argument("--parallelism", type=int, default=4)

    insp = sub.add_parser("inspect", help="describe a container without decrypting it")
    insp.add_argument("--in", dest="infile", help="input path (default: stdin)")

    sub.add_parser("selftest", help="round-trip this implementation against itself")
    args = ap.parse_args()

    if args.cmd == "selftest":
        return _selftest()

    if args.cmd == "inspect":
        try:
            return _inspect(read_container(args.infile))
        except KeymError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1

    try:
        data = (
            read_container(args.infile)
            if args.cmd == "decrypt"
            else _read_bytes(args.infile)
        )
        key_file = open(args.key_file, "rb").read() if args.key_file else None
        password = resolve_password(args.password, confirm=(args.cmd == "encrypt"))
    except KeymError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.cmd == "encrypt":
        kdf_id = KDF_PBKDF2 if args.kdf == "pbkdf2" else KDF_ARGON2ID
        params = (
            Pbkdf2Params(args.iterations)
            if kdf_id == KDF_PBKDF2
            else Argon2idParams(args.time_cost, args.memory_kib, args.parallelism)
        )
        cipher_id = {"aes": CIPHER_AES_256_GCM, "chacha": CIPHER_CHACHA20_POLY1305, "chained": CIPHER_CHAINED}[args.cipher]
        try:
            out = encrypt(data, password, key_file, kdf_id, params, cipher_id)
        except KeymError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
    else:
        try:
            out = decrypt(data, password, key_file)
        except KeymError as exc:
            # Deliberately undifferentiated (FORMAT.md section 10). The hint
            # below is about *inputs the user controls*, not about which check
            # failed — it must not become an oracle.
            print(f"error: {exc}", file=sys.stderr)
            print(
                "hint: this means the password, the key file, or the data itself is "
                "not right. Run `inspect` to see whether the container expects a key "
                "file.",
                file=sys.stderr,
            )
            return 1

    if args.outfile:
        # 0600. On the decrypt branch `out` is the plaintext, and
        # `open(path, "wb")` creates at 0666 & ~umask — 0644 on a stock account.
        # keym2.py was fixed for this; this file was not, and it is the one an
        # heir with a *v1* backup runs. A v1 backup is by definition an older
        # one, so the person opening it is more likely to be an heir than the
        # author, which is the wrong way round for the file to be the laxer of
        # the two.
        #
        # Kept as a local rather than imported from keym2.py: these two
        # references are deliberately independent implementations, and a shared
        # helper would make a bug in one a bug in both.
        with _open_private(args.outfile) as fh:
            fh.write(out)
    else:
        sys.stdout.buffer.write(out)
    return 0


def _read_bytes(path: str | None) -> bytes:
    """
    Read `path`, or stdin when there is none.

    A mistyped path is the most ordinary mistake a person makes, and an
    unguarded `open()` answered it with a FileNotFoundError traceback. To
    someone opening a dead relative's backup, a Python traceback reads as
    "the file is destroyed" — which is exactly the wrong conclusion to hand
    them about a file they simply named wrong.
    """
    if not path:
        return sys.stdin.buffer.read()
    try:
        with open(path, "rb") as fh:
            return fh.read()
    except OSError as exc:
        raise KeymError(f"cannot read {path}: {exc.strerror}") from None


def _open_private(path: str):
    """
    Open `path` for writing, readable only by its owner. See the call site.

    O_CREAT's mode is ignored when the file already exists, so an existing 0644
    file would otherwise keep its bits; `fchmod` on the descriptor just opened
    covers that without the race a path-based `chmod` would have. Where it is
    unavailable or refused — Windows, a FIFO, a filesystem with no mode bits —
    the write still goes ahead: failing to narrow permissions is not a reason
    to refuse someone their own plaintext.

    O_NOFOLLOW where the platform has it, so a symlink planted at `--out` is
    refused rather than written through. Not O_EXCL: refusing to overwrite
    would strand the ordinary case of re-running a command after a typo, and
    this is a recovery tool.
    """
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags, 0o600)
    except OSError as exc:
        if exc.errno == errno.ELOOP:
            raise KeymError(
                f"refusing to write {path}: it is a symbolic link"
            ) from None
        raise KeymError(f"cannot write {path}: {exc.strerror}") from None
    if hasattr(os, "fchmod"):
        try:
            os.fchmod(fd, 0o600)
        except OSError:
            pass
    return os.fdopen(fd, "wb")


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeymError as _e:
        print(f"error: {_e}", file=sys.stderr)
        raise SystemExit(1) from None
